name: Deploy valentinl.de to Uberspace
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run build
      - name: Deploy using Rsync
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -avrh --delete
          path: dist/
          remote_path: /var/www/virtual/${{ vars.SSH_USERNAME }}/valentinl.de
          remote_host: ${{ vars.SSH_HOST }}
          remote_user: ${{ vars.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
